.TH syslog 8
.SH NAME
.B syslog
\- manages the system log
.SH SYNOPSIS
.B syslog
.SH DESCRIPTION
Receives log messages from other processes and writes them the system log.
.SH FILES
.TP
.B /var/log/syslog
The system log
.TP
.B /var/log/kern.log
The kernel log
.TP
.B /dev/log
The socket messages are received from
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B daemon(8), klog(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
